# Generated by Django 2.1.5 on 2019-02-02 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Turorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Turorial_title', models.CharField(max_length=200)),
                ('Turorial_content', models.TextField()),
                ('Turorial_published', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
