# Generated by Django 2.1.5 on 2019-02-02 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Turorial',
            new_name='Tutorial',
        ),
        migrations.RenameField(
            model_name='tutorial',
            old_name='Turorial_content',
            new_name='Tutorial_content',
        ),
        migrations.RenameField(
            model_name='tutorial',
            old_name='Turorial_published',
            new_name='Tutorial_published',
        ),
        migrations.RenameField(
            model_name='tutorial',
            old_name='Turorial_title',
            new_name='Tutorial_title',
        ),
    ]
