# Generated by Django 2.1.4 on 2019-02-02 21:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190202_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='Tutorial_edit',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Date Edited'),
        ),
    ]
