# Generated by Django 2.1.5 on 2019-02-11 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190211_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='Tutorial_slug',
            field=models.CharField(default=1, max_length=200),
        ),
    ]
